"""Change user_id to BigInteger

Revision ID: 188605f1cff9
Revises: e3662ca4c3f6
Create Date: 2025-04-03 15:03:07.402691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '188605f1cff9'
down_revision = 'e3662ca4c3f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('expenses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expenses', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('expenses', 'amount_uah',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('expenses', 'amount_usd',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('ix_expenses_title', table_name='expenses')
    op.drop_index('ix_expenses_user_id', table_name='expenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_expenses_user_id', 'expenses', ['user_id'], unique=False)
    op.create_index('ix_expenses_title', 'expenses', ['title'], unique=False)
    op.alter_column('expenses', 'amount_usd',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('expenses', 'amount_uah',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('expenses', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
